a. Extraer la información del archivo

In [274]:
import pandas as pd
vacunacion=pd.read_csv('/content/sample_data/country_vaccinations.csv')


b. Mostrar la estructura y tipos de datos de cada columna para identificar qué operaciones puedes realizar con cada una de ellas, asegurandote que las columnas con fechas sean del tipo datetime64.

In [275]:
vacunacion['date']=pd.to_datetime(vacunacion['date'])
vacunacion.info()
vacunacion.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86512 entries, 0 to 86511
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              86512 non-null  object
 1   iso_code                             86512 non-null  object
 2   date                                 86512 non-null  datetime64[ns]
 3   total_vaccinations                   43607 non-null  float64
 4   people_vaccinated                    41294 non-null  float64
 5   people_fully_vaccinated              38802 non-null  float64
 6   daily_vaccinations_raw               35362 non-null  float64
 7   daily_vaccinations                   86213 non-null  float64
 8   total_vaccinations_per_hundred       43607 non-null  float64
 9   people_vaccinated_per_hundred        41294 non-null  float64
 10  people_fully_vaccinated_per_hundred  38802 non-null  float64
 11  daily_vaccinations_per_million       86213 non-null  float64
 12  vaccines                             86512 non-null  object
 13  source_name                          86512 non-null  object
 14  source_website                       86512 non-null  object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 9.9+ MB

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

c. Determinar la cantidad de vacunas aplicadas de cada compañía (en base a como lo reporta cada país en la columna vaccines)

In [276]:
vacunacion[['vaccines','source_name']].groupby('source_name').count()

                                                   vaccines
source_name
Africa Centres for Disease Control and Prevention      2780
COVID-19 Malta Public Health Response Team              436
COVID-19 Vaccine Information Platform                   441
Centers for Disease Control and Prevention              471
Costa Rican Social Security Fund                        460
...                                                     ...
Secretary of Health                                     461
State governments via coronavirusbra1.github.io         437
Statens Serum Institute                                 476
Taiwan Centers for Disease Control                      374
World Health Organization                             26822

[81 rows x 1 columns]

d. Obtener la cantidad de vacunas aplicadas en todo el mundo

In [277]:
print('la cantidad de vacunas en el mundo es:',vacunacion['total_vaccinations'].sum())
print('la cantidad de vacunas aplicadas en el mundo es:',vacunacion['people_vaccinated'].sum())
print('la cantidad de gente vacunada completamente en el mundo es:',vacunacion['people_fully_vaccinated'].sum())

la cantidad de vacunas en el mundo es: 2002854013761.0
la cantidad de vacunas aplicadas en el mundo es: 731113482252.0
la cantidad de gente vacunada completamente en el mundo es: 548594310708.0

e. Calcular el promedio de vacunas aplicadas por país

In [278]:
vacunacion[['country','people_vaccinated']].groupby('country').mean()

                   people_vaccinated
country
Afghanistan             2.283978e+06
Albania                 7.691666e+05
Algeria                 5.667521e+06
Andorra                 3.393784e+04
Angola                  4.030443e+06
...                              ...
Wales                   2.024054e+06
Wallis and Futuna       4.919744e+03
Yemen                   3.887164e+05
Zambia                  3.126864e+05
Zimbabwe                2.405831e+06

[223 rows x 1 columns]

f. Determinar la cantidad de vacunas aplicadas el día 29/01/21 en todo el mundo

In [279]:
vacunacion=vacunacion[vacunacion['date']=="29-01-21"]
vacunacion[['daily_vaccinations','date']].groupby('date').sum()

            daily_vaccinations
date
2021-01-29           4884052.0

g. Crear un dataframe nuevo denoninado conDiferencias que contenga los datos originales y una columna derivada (diferencias) con las diferencias de aplicación entre las columnas daily_vaccionations y daily_vaccionations_raw

In [280]:

conDiferencias=pd.read_csv('/content/sample_data/country_vaccinations.csv')
conDiferencias['date']=pd.to_datetime(conDiferencias['date'])
conDiferencias['diferencias']=conDiferencias['daily_vaccinations']-conDiferencias['daily_vaccinations_raw']
conDiferencias['diferencias']

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
86507   -69634.0
86508   -16657.0
86509    37318.0
86510    11293.0
86511    -1618.0
Name: diferencias, Length: 86512, dtype: float64

h. Obtener el período de tiempo entre el registro con fecha más reciente y el registro con fecha más antigua

In [281]:
print('Fecha del primer reporte: ', conDiferencias['date'].min())
print('Fecha del último reporte: ', conDiferencias['date'].max())

Fecha del primer reporte:  2020-12-02 00:00:00
Fecha del último reporte:  2022-03-29 00:00:00

i. Crear un dataframe nuevo denominado conCantidad que contenga los datos originales y una columna derivada (canVac) con la cantidad de vacunas utilizadas cada día (usar la columna vaccines y separar por el carácter / )

In [282]:
conCantidad=pd.read_csv('/content/sample_data/country_vaccinations.csv')
conCantidad['date']=pd.to_datetime(conCantidad['date'])
conCantidad['canVac']=conCantidad['vaccines'].str.split('/').str.len()
conCantidad['canVac']

0        4
1        4
2        4
3        4
4        4
        ..
86507    3
86508    3
86509    3
86510    3
86511    3
Name: canVac, Length: 86512, dtype: int64

j. Generar un dataframe denominado antes20 con todos los registros que se hayan realizado antes del 20 de diciembre de 2020.

In [283]:
antes20=pd.read_csv('/content/sample_data/country_vaccinations.csv')
antes20['date']=pd.to_datetime(antes20['date'])
antes20=antes20.query("date < '20-12-20'")
antes20.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
13403,Canada,CAN,2020-12-14,5.0,5.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13404,Canada,CAN,2020-12-15,727.0,727.0,NaN,722.0,722.0,0.00,0.00,NaN,19.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13405,Canada,CAN,2020-12-16,3025.0,3025.0,NaN,2298.0,1510.0,0.01,0.01,NaN,40.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13406,Canada,CAN,2020-12-17,7279.0,7279.0,NaN,4254.0,2425.0,0.02,0.02,NaN,64.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13407,Canada,CAN,2020-12-18,11296.0,11296.0,NaN,4017.0,2823.0,0.03,0.03,NaN,74.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html

k. Obtener un dataframe denominado pfizer con todos los registros donde se haya utilizado la vacuna Pfizer.

In [284]:
pfizer=pd.read_csv('/content/sample_data/country_vaccinations.csv')
pfizer['date']=pd.to_datetime(pfizer['date'])
pfizer=pfizer[pfizer['vaccines'].str.contains('Pfizer')] 
pfizer.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

l. Almacenar los dataframes generados (conDiferencias,conCantidad,antes20 y pfizer) en un archivo de Excel denominado resultadosReto.xlsx, donde cada dataframe ocupe una hoja diferente. Se recomienda ver la documentación de pd.ExcelWriter

In [285]:
with pd.ExcelWriter("/content/sample_data/resultadosReto.xlsx") as writer:
   
    # use to_excel function and specify the sheet_name and index
    # to store the dataframe in specified sheet
    
    conDiferencias.to_excel(writer, sheet_name='conDiferencias')
    conCantidad.to_excel(writer, sheet_name='conCantidad')
    antes20.to_excel(writer, sheet_name='antes20')
    pfizer.to_excel(writer, sheet_name='pfizer')